module.exports = {
  PLAYERS_RECEIVE: 'PLAYERS_RECEIVE',
  PLAYER_REMOVE: 'PLAYER_REMOVE',

  GAMES_RECEIVE: 'GAMES_RECEIVE',
  GAME_REMOVE: 'GAME_REMOVE',

  SCORES_RECEIVE: 'SCORES_RECEIVE',
  SCORE_REMOVE: 'SCORE_REMOVE',
};
