fastlane_version "1.68.0"
default_platform :android

platform :android do
  desc "Deploy a new version to the Google Play Store"
  lane :beta do
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "android/"
    )
    desc "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    supply(
      track: "alpha",
      apk_paths: ["#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"]
    )
  end
end

platform :ios do
  desc "Responsible for building and signing the app"
  private_lane :build_app do |options|
    deliver(
      force: true,
      team_name: "antoine lenoir|297178063"
    )

    match(type: "appstore")

    increment_build_number(
      xcodeproj: "ios/king.xcodeproj"
    )

    gym(
      project: "ios/king.xcodeproj",
      scheme: "king",
      output_directory: "./fastlane/Release/",
    )
  end

  desc "Build and upload a new build to Apple TestFlight"
  desc "This action will also do a build version bump and push it to git."
  lane :beta do
    build_app

    pilot

    clean_build_artifacts(
      exclude_pattern: ".*\.mobileprovision"
    )
  end
end
